---
title: "julid24_OriginalHomeworkCode_05"
author: "Julianna D."
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_float: true
---
# Boostrapping Standard Errors and CIs for Linear Models
> Using bootstrapping, we can estimate standard errors and CIs around regression parameters, such as β coefficients.

## Problem 1
Using the “KamilarAndCooperData.csv” dataset, run a linear regression looking at log(HomeRange_km2) in relation to log(Body_mass_female_mean) and report your β coeffiecients (slope and intercept).

```{r}

```

## Problem 2
Then, use bootstrapping to sample from your data 1000 times with replacement, each time fitting the same model and calculating the same coefficients. This generates a sampling distribution for each β coefficient.

> Estimate the standard error for each of your β coefficients as the standard deviation of the sampling distribution from your bootstrap and determine the 95% CI for each of your β coefficients based on the appropriate quantiles from your sampling distribution.

> How does the former compare to the SE estimated from your entire dataset using the formula for standard error implemented in lm()?

> How does the latter compare to the 95% CI estimated from your entire dataset?